import json
import requests
from config.settings import JIRA_USER, JIRA_TOKEN, CLOUD_ID, AI_PREFIX, DEBUG_MODE, DebugMode
from jira.utils import extract_adf_text, jira_request


def extract_comment_text(comment: dict) -> str:
    return extract_adf_text(comment.get("body", {}))


def has_ai_comment(fields: dict) -> bool:
    # Checks all comments including internal ones — safe since this data is never sent to the AI
    comments = fields.get("comment", {}).get("comments", [])
    return any(AI_PREFIX in extract_comment_text(c) for c in comments)


RESTRICTED_ISSUE_SKIP_NOTICE = (
    "This issue has a **Jira security level** set (the ticket is restricted — e.g. not visible to all users). "
    "To avoid sending ticket content to the **external AI** service, **no automated analysis was run**.\n\n"
    "**How to get an analysis:**\n"
    "- Create or use a **non-restricted** ticket with the same technical question and use the `ai-assist` label or `/ai-assist` comment there, or\n"
    "- Add a **redacted** description that your policy allows to be processed externally, or\n"
    "- Run the agent **locally** with `ISSUE_KEY` only if your org policy permits processing this issue's data.\n\n"
    "_If restricted issues should be analyzed in your environment, update agent policy or configuration accordingly._"
)


@jira_request
def post_comment(issue_key: str, agent_response: str):
    disclaimer = "\n\n---\n_⚠️ This comment was generated by an AI agent and may not be fully accurate. Please verify before acting on it._"
    if DebugMode.DISABLE_JIRA in DEBUG_MODE:
        print(f"[DEBUG] Would post comment on {issue_key}: {agent_response}")
        return
    full_comment = AI_PREFIX + agent_response + disclaimer
    url = f"https://api.atlassian.com/ex/jira/{CLOUD_ID}/rest/api/3/issue/{issue_key}/comment"
    headers = {"Accept": "application/json", "Content-Type": "application/json"}

    body_dict = {
        "body": {
            "type": "doc",
            "version": 1,
            "content": [
                {
                    "type": "paragraph",
                    "content": [{"type": "text", "text": full_comment}]
                }
            ]
        }
    }
    body_dict["visibility"] = {"type": "group", "value": "Red Hat Employee"}

    response = requests.post(url, data=json.dumps(body_dict), headers=headers, auth=(JIRA_USER, JIRA_TOKEN), timeout=10)
    if response.status_code == 201:
        print(f"Comment posted successfully on {issue_key}.")
    else:
        print(f"Failed to post comment on {issue_key}: {response.status_code} - {response.text}")


def post_restricted_issue_skip_notice(issue_key: str) -> None:
    """Post employee-visible comment; uses same AI_PREFIX as normal replies so we do not re-trigger analysis."""
    post_comment(issue_key, RESTRICTED_ISSUE_SKIP_NOTICE)
